### ISSUE TITLE
Cannot interchange access_token for id_token

### ISSUE THREAD

**Issue by skyred** [abouroubi/passport-google-verify-token#14]
Even though both `access_token` and `id_token` are JWT tokens, they are different types of tokens, see https://cloud.google.com/docs/authentication/token-types

When this app is verifying Google tokens in https://github.com/abouroubi/passport-google-verify-token/blob/4ed21fd54ccb1892a5aef783d0137531e0c2f024/src/strategy.ts#L123-L127

It only calls `verifyIdToken()` method, which only supports `id_token`, therefore, if the input token is an `access_token`, the application will throw "Wrong number of segments in token" error.

Proposed solution:
1. Make a configuration to let the application decides which type of token to accept, then call the corresponding method.

**Comment by abouroubi** [comment]
Hello @skyred , the first goal of this package is to check the id token when the user used Google Login in Android client for example, the validation of accessToken was not needed.

If you think this feature is valuable for you, I'm open to PRs

**Comment by abouroubi** [comment]
The PR #15  has added this feautre.

**Comment by skyred** [comment]
@abouroubi Can you please push v.2.3.3 to NPM, which still has v2.2.0 as latest

**Comment by abouroubi** [comment]
Unfortunately the contributor who opened the PR did not write the tests for it.
So the Unit Tests are not passing anymore, and I don't have the time to fix them.

Feel free to open a PR to fix it, I'll be happy to merge it and publish the new version.
